In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:

import pandas as pd

In [ ]:
df = pd.read_csv('/content/crickeet-t20.csv')

In [ ]:
df

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15
0,0.0,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
1,NaN,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
2,1.0,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.1,1905,138.21,4,19,6,234,120,NaN
3,2.0,MJ Guptill (NZ),2009-2019,83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,NaN
4,3.0,Shoaib Malik (ICC/PAK),2006-2019,111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002,1.0,SG Whittingham (SCOT),2018-2018,3,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2003,2.0,LJ Woodcock (NZ),2010-2011,3,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2004,3.0,Zamir Khan (AFG),2012-2012,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2005,4.0,S Zargar (Mex),2019-2019,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2006,5.0,Ziaur Rahman (AFG),2019-2019,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN

In [ ]:
df = df.rename(columns = {'Mat':'Matches','NO':'NOt_Outs','HS':'Highest_inng_rate','BF':'Balls_faced','SR':'Striking_rate'})

,Unnamed: 0,Player,Span,Matches,Inns,NOt_Outs,Runs,Highest_inng_rate,Ave,Balls_faced,Striking_rate,100,50,0,4s,6s,Unnamed: 15
0,0.0,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
1,NaN,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
2,1.0,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.1,1905,138.21,4,19,6,234,120,NaN
3,2.0,MJ Guptill (NZ),2009-2019,83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,NaN
4,3.0,Shoaib Malik (ICC/PAK),2006-2019,111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002,1.0,SG Whittingham (SCOT),2018-2018,3,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2003,2.0,LJ Woodcock (NZ),2010-2011,3,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2004,3.0,Zamir Khan (AFG),2012-2012,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2005,4.0,S Zargar (Mex),2019-2019,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN
2006,5.0,Ziaur Rahman (AFG),2019-2019,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN

In [ ]:
df.isnull().any()

Unnamed: 0      True
Player         False
Span           False
Mat            False
Inns           False
NO             False
Runs           False
HS             False
Ave            False
BF             False
SR             False
100            False
50             False
0              False
4s             False
6s             False
Unnamed: 15     True
dtype: bool

In [ ]:
df['BF']=df['BF'].fillna(0)

In [ ]:
df['Strike_Rate']=df['Striking_rate'].fillna(0)

In [ ]:
df[df['Player']=='V Kohli (INDIA)']

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15,Strike_Rate
0,0.0,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
1,NaN,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2002    False
2003    False
2004    False
2005    False
2006    False
Length: 2007, dtype: bool

In [ ]:
df[df['Player'].duplicated()==1]

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15,Strike_Rate
1,NaN,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)

In [ ]:
df[df['Player'].isin(['V Kohli (INDIA)'])]

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15,Strike_Rate
0,0.0,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
1,NaN,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df[df['Player'].isin(['V Kohli (INDIA)'])]

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15,Strike_Rate
0,0.0,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
1,NaN,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)

In [ ]:
df['Span'].str.split(pat='-')

0       [V Kohli (INDIA)]
1       [V Kohli (INDIA)]
2            [2007, 2019]
3            [2009, 2019]
4            [2006, 2019]
              ...
2002         [2018, 2018]
2003         [2010, 2011]
2004         [2012, 2012]
2005         [2019, 2019]
2006         [2019, 2019]
Name: Span, Length: 2007, dtype: object

In [ ]:
df['Span'].str.split(pat='-').str[1]

0        NaN
1        NaN
2       2019
3       2019
4       2019
        ...
2002    2018
2003    2011
2004    2012
2005    2019
2006    2019
Name: Span, Length: 2007, dtype: object

In [ ]:
df['Rookie_year']=df['Span'].str.split(pat='-').str[0]

In [ ]:
df['final_year']=df['Span'].str.split(pat='-').str[0]

In [ ]:
df

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15,Strike_Rate,Rookie_year,final_year
0,0.0,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
1,NaN,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
2,1.0,RG Sharma (INDIA),2007-2019,104,96,14,2633,118,32.1,1905,138.21,4,19,6,234,120,NaN,138.21,2007,2007
3,2.0,MJ Guptill (NZ),2009-2019,83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,NaN,134.58,2009,2009
4,3.0,Shoaib Malik (ICC/PAK),2006-2019,111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,NaN,124.06,2006,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002,1.0,SG Whittingham (SCOT),2018-2018,3,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2018,2018
2003,2.0,LJ Woodcock (NZ),2010-2011,3,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2010,2010
2004,3.0,Zamir Khan (AFG),2012-2012,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2012,2012
2005,4.0,S Zargar (Mex),2019-2019,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2019,2019
2006,5.0,Ziaur Rahman (AFG),2019-2019,1,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2019,2019

In [ ]:
df.drop(['Span'],axis=1)

,Unnamed: 0,Player,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Unnamed: 15,Strike_Rate,Rookie_year,final_year
0,0.0,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
1,NaN,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA)
2,1.0,RG Sharma (INDIA),104,96,14,2633,118,32.1,1905,138.21,4,19,6,234,120,NaN,138.21,2007,2007
3,2.0,MJ Guptill (NZ),83,80,7,2436,105,33.36,1810,134.58,2,15,2,215,113,NaN,134.58,2009,2009
4,3.0,Shoaib Malik (ICC/PAK),111,104,30,2263,75,30.58,1824,124.06,0,7,1,186,61,NaN,124.06,2006,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002,1.0,SG Whittingham (SCOT),3,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2018,2018
2003,2.0,LJ Woodcock (NZ),3,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2010,2010
2004,3.0,Zamir Khan (AFG),1,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2012,2012
2005,4.0,S Zargar (Mex),1,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2019,2019
2006,5.0,Ziaur Rahman (AFG),1,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,2019,2019

In [ ]:
df['Player'].str.split(pat='-')

0              [V Kohli (INDIA)]
1              [V Kohli (INDIA)]
2            [RG Sharma (INDIA)]
3              [MJ Guptill (NZ)]
4       [Shoaib Malik (ICC/PAK)]
                  ...
2002     [SG Whittingham (SCOT)]
2003          [LJ Woodcock (NZ)]
2004          [Zamir Khan (AFG)]
2005            [S Zargar (Mex)]
2006        [Ziaur Rahman (AFG)]
Name: Player, Length: 2007, dtype: object

In [ ]:
df['Player'].str.split(pat='(')

0              [V Kohli , INDIA)]
1              [V Kohli , INDIA)]
2            [RG Sharma , INDIA)]
3              [MJ Guptill , NZ)]
4       [Shoaib Malik , ICC/PAK)]
                  ...
2002     [SG Whittingham , SCOT)]
2003          [LJ Woodcock , NZ)]
2004          [Zamir Khan , AFG)]
2005            [S Zargar , Mex)]
2006        [Ziaur Rahman , AFG)]
Name: Player, Length: 2007, dtype: object

In [ ]:
df['Country']=df['Player'].str.split(pat='(').str[1]

In [ ]:
df['Country'] = df['Country'].str.split(pat =')').str[0]

In [ ]:
df['Country']

0         INDIA
1         INDIA
2         INDIA
3            NZ
4       ICC/PAK
         ...
2002       SCOT
2003         NZ
2004        AFG
2005        Mex
2006        AFG
Name: Country, Length: 2007, dtype: object

In [ ]:
df['Player'] = df['Player'].str.split(pat='(').str[0]

In [ ]:
df.head()

,Unnamed: 0,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,...,0,4s,6s,Unnamed: 15,Strike_Rate,Rookie_year,final_year,Player_name,Player_Country,Country
0,0.0,V Kohli,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),...,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),INDIA
1,NaN,V Kohli,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),...,V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),V Kohli (INDIA),INDIA
2,1.0,RG Sharma,2007-2019,104,96,14,2633,118,32.1,1905,...,6,234,120,NaN,138.21,2007,2007,RG Sharma (INDIA),RG Sharma (INDIA),INDIA
3,2.0,MJ Guptill,2009-2019,83,80,7,2436,105,33.36,1810,...,2,215,113,NaN,134.58,2009,2009,MJ Guptill (NZ),MJ Guptill (NZ),NZ
4,3.0,Shoaib Malik,2006-2019,111,104,30,2263,75,30.58,1824,...,1,186,61,NaN,124.06,2006,2006,Shoaib Malik (ICC/PAK),Shoaib Malik (ICC/PAK),ICC/PAK

In [ ]:
df.dtypes

Unnamed: 0        float64
Player             object
Span               object
Mat                object
Inns               object
NO                 object
Runs               object
HS                 object
Ave                object
BF                 object
SR                 object
100                object
50                 object
0                  object
4s                 object
6s                 object
Unnamed: 15        object
Strike_Rate        object
Rookie_year        object
final_year         object
Player_name        object
Player_Country     object
Country            object
dtype: object